# Generated by Django 5.2.8 on 2025-12-05 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False, help_text="Whether to hide the user's identity")),
                ('team', models.ForeignKey(blank=True, help_text='Team the feedback is for (optional for admins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='teams.team')),
                ('user', models.ForeignKey(help_text='User who gave the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='team_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_feedbacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='team_feedba_created_7cd730_idx'), models.Index(fields=['team', 'is_anonymous'], name='team_feedba_team_id_91b46a_idx')],
            },
        ),
    ]
