# Generated by Django 5.2.8 on 2025-12-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamfeedback',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                help_text='Team the feedback is for (optional for admins)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedbacks',
                to='teams.team'
            ),
        ),
    ]