# Generated by Django 5.2.8 on 2025-11-22 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'moods',
                'ordering': ['value'],
            },
        ),
    ]
