# Generated by Django 5.2.8 on 2025-11-22 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=255)),
                ('metadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='event_logs_timesta_b10417_idx'), models.Index(fields=['event_name'], name='event_logs_event_n_8db346_idx')],
            },
        ),
        migrations.CreateModel(
            name='PulseLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mood', models.IntegerField()),
                ('workload', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_local', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('week_index', models.IntegerField()),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pulse_logs', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pulse_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='pulse_logs_timesta_3e7be8_idx'), models.Index(fields=['user', 'year', 'week_index'], name='pulse_logs_user_id_29f2ef_idx')],
            },
        ),
    ]
